<Project>
	<ItemGroup>
		<Content Include="..\.editorconfig">
			<Link>Properties\.editorconfig</Link>
		</Content>
		<AdditionalFiles Include="..\allowed_words.dic">
			<Link>Properties\allowed_words.dic</Link>
		</AdditionalFiles>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="StyleCop.Analyzers">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
</Project>