<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<PlatformTarget>x86</PlatformTarget>
		<RootNamespace>Skyline.DataMiner.SDM.ObjectLinking.Tests</RootNamespace>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UseVSTest>true</UseVSTest>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="MSTest.TestAdapter" />
		<PackageReference Include="MSTest.TestFramework" />
		<PackageReference Include="FluentAssertions" />
		<PackageReference Include="PublicApiGenerator" />
		<PackageReference Include="Verify.MSTest" />
		<PackageReference Include="FluentAssertions" />
		<PackageReference Include="Moq" />
		<PackageReference Include="Skyline.DataMiner.Utils.DOM" />
		<PackageReference Include="Skyline.DataMiner.Dev.Automation" />
		<PackageReference Include="Skyline.DataMiner.Dev.Utils.SDM.Abstractions" />
		<PackageReference Include="Skyline.DataMiner.SDM.SourceGenerator.Runtime" />
		<PackageReference Include="Skyline.DataMiner.SDM.Linq" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\API.Common\ObjectLinking.Common.csproj" />
		<ProjectReference Include="..\Install\ObjectLinking.Install.csproj" />
	</ItemGroup>
</Project>
