<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<!--<TargetFramework>netstandard2.0</TargetFramework>-->
		<!--<TargetFrameworks>netstandard2.0;net48</TargetFrameworks>-->
		<PlatformTarget>AnyCpu</PlatformTarget>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<AssemblyName>Skyline.DataMiner.Dev.Utils.SDM.ObjectLinking.Common</AssemblyName>
		<RootNamespace>Skyline.DataMiner.SDM.ObjectLinking</RootNamespace>
		<Version>0.2.0-B002</Version>
		<PackageTags>Skyline;DataMiner</PackageTags>
		<PackageProjectUrl>https://skyline.be</PackageProjectUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
		<PackageIcon>Icon.png</PackageIcon>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Authors>SkylineCommunications</Authors>
		<Company>Skyline Communications</Company>
		<Description>Contains the common models and helper classes to interact with the standard object linking model.</Description>
		<RepositoryType>git</RepositoryType>
		<RepositoryUrl>https://github.com/SkylineCommunications/SLC-SDM-ObjectLinking</RepositoryUrl>
	</PropertyGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="" />
		<None Include="LICENSE.txt" Pack="true" PackagePath="" />
		<None Include="nuget\Icon.png" Pack="true" PackagePath="" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" />
		<PackageReference Include="Skyline.DataMiner.Files.Skyline.DataMiner.Storage.Types" />
		<PackageReference Include="Skyline.DataMiner.Files.SLNetTypes" />
		<PackageReference Include="Skyline.DataMiner.SDM" />
		<PackageReference Include="Skyline.DataMiner.Utils.SecureCoding.Analyzers">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Skyline.DataMiner.Dev.Utils.SDM.ObjectLinking.Automation" />
		<InternalsVisibleTo Include="Skyline.DataMiner.Dev.Utils.SDM.ObjectLinking.GQI" />
		<InternalsVisibleTo Include="Skyline.DataMiner.Dev.Utils.SDM.ObjectLinking.Protocol" />
		<InternalsVisibleTo Include="ObjectLinking.Install" />
		<InternalsVisibleTo Include="ObjectLinking.CommonTests" />
	</ItemGroup>

	<Import Project="..\Shared\Shared.projitems" Label="Shared" />

	<!-- Can be used to set the location of your local nuget store to copy to -->
	<Import Project="../Directory.Build.props.user" Condition="Exists('../Directory.Build.props.user')" />
	<Target Name="CopyNuGetPackage" AfterTargets="Pack" Condition="'$(NuGetStorePath)' != '' and '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
		<Copy SourceFiles="$(OutputPath)..\$(PackageId).$(PackageVersion).nupkg" DestinationFolder="$(NuGetStorePath)\$(PackageId)" />
	</Target>
</Project>