//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DOM Code Generator automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DomHelpers
{
	using System;
	using System.Linq;

	using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
	using Skyline.DataMiner.Net.ManagerStore;
	using Skyline.DataMiner.Net.Messages;
	using Skyline.DataMiner.Net.Sections;

	/// <summary>
	/// Serves as the abstract base class for wrapper classes that provide access to DOM instances.
	/// The <see cref="DomInstanceBase"/> class defines the common functionality and structure for interacting with DOM objects stored in the database, serving as a foundation for derived classes that wrap specific DOM instances.
	/// </summary>
	internal abstract class DomInstanceBase : IEquatable<DomInstanceBase>
	{
		protected DomInstanceBase(DomDefinitionId definitionId)
		{
			if (definitionId == null)
				throw new ArgumentNullException("definitionId");
			domInstance = new DomInstance { DomDefinitionId = definitionId };
		}

		protected DomInstanceBase(DomDefinitionId definitionId, Guid id)
		{
			if (definitionId == null)
				throw new ArgumentNullException("definitionId");
			if (id == Guid.Empty)
				throw new ArgumentException("The id cannot be an empty guid", nameof(id));
			domInstance = new DomInstance
			{
				ID = new DomInstanceId(id)
				{ ModuleId = definitionId.ModuleId },
				DomDefinitionId = definitionId
			};
		}

		protected DomInstanceBase(DomInstance domInstance)
		{
			if (domInstance == null)
				throw new ArgumentNullException("domInstance");
			this.domInstance = domInstance;
		}

		/// <summary>
		/// Gets the Module ID of the DOM Instance.
		/// </summary>
		public String ModuleId
		{
			get
			{
				return domInstance.DomDefinitionId.ModuleId;
			}
		}

		/// <summary>
		/// Gets the ID of the DOM Instance.
		/// </summary>
		public DomInstanceId ID
		{
			get
			{
				return domInstance.ID;
			}
		}

		/// <summary>
		/// Gets the name of the DOM Instance.
		/// </summary>
		public String Name
		{
			get
			{
				return domInstance.Name;
			}
		}

		/// <summary>
		/// Gets the Status ID of the DOM Instance.
		/// </summary>
		public String StatusId
		{
			get
			{
				return domInstance.StatusId;
			}
		}

		/// <summary>
		/// Gets the underlying DOM Instance.
		/// </summary>
		public DomDefinitionId DomDefinitionId
		{
			get
			{
				return domInstance.DomDefinitionId;
			}
		}

		protected DomInstance domInstance { get; set; }

		/// <summary>
		/// Gets the datetime when the DOM Instance was created in UTC.
		/// </summary>
		public DateTimeOffset CreatedAt
		{
			get
			{
				return ((ITrackCreatedAt)domInstance).CreatedAt;
			}
		}

		/// <summary>
		/// Gets the user that created the DOM Instance.
		/// </summary>
		public string CreatedBy
		{
			get
			{
				return ((ITrackCreatedBy)domInstance).CreatedBy;
			}
		}

		/// <summary>
		/// Gets the datetime when the DOM Instance was last modified in UTC.
		/// </summary>
		public DateTimeOffset LastModified
		{
			get
			{
				return ((ITrackLastModified)domInstance).LastModified;
			}
		}

		/// <summary>
		/// Gets the user that last modified the DOM Instance.
		/// </summary>
		public string LastModifiedBy
		{
			get
			{
				return ((ITrackLastModifiedBy)domInstance).LastModifiedBy;
			}
		}

		public static implicit operator DomInstanceId(DomInstanceBase instance)
		{
			return instance.ID;
		}

		public static implicit operator DomInstance(DomInstanceBase instance)
		{
			return instance.ToInstance();
		}

		public static bool operator ==(DomInstanceBase left, DomInstanceBase right)
		{
			if (left is null)
			{
				return right is null;
			}

			return left.Equals(right);
		}

		public static bool operator !=(DomInstanceBase left, DomInstanceBase right)
		{
			return !(left == right);
		}

		/// <summary>
		/// Deletes this DOM Instance from the database.
		/// </summary>
		/// <param name="messageHandler">The connection to the DataMiner system.</param>
		public void Delete(Func<DMSMessage[], DMSMessage[]> messageHandler)
		{
			Delete(new DomHelper(messageHandler, ModuleId));
		}

		/// <summary>
		/// Deletes this DOM Instance from the database.
		/// </summary>
		/// <param name="helper">The connection to the DataMiner system.</param>
		public void Delete(DomHelper helper)
		{
			helper.DomInstances.Delete(domInstance);
		}

		/// <summary>
		/// Saves this DOM Instance to the database.
		/// </summary>
		/// <param name="messageHandler">The connection to the DataMiner system.</param>
		public void Save(Func<DMSMessage[], DMSMessage[]> messageHandler)
		{
			Save(new DomHelper(messageHandler, ModuleId));
		}

		/// <summary>
		/// Saves this DOM Instance to the database.
		/// </summary>
		/// <param name="helper">The connection to the DataMiner system.</param>
		public abstract void Save(DomHelper helper);
		/// <summary>
		/// Return the DOM Instance object with all the fields filled in according to this object.
		/// </summary>
		public DomInstance ToInstance()
		{
			BeforeToInstance();
			var instance = InternalToInstance();
			AfterToInstance();
			return instance;
		}

		/// <summary>
		/// Optional method that runs before the internal ToInstance method runs.
		/// </summary>
		protected virtual void BeforeToInstance()
		{
		}

		/// <summary>
		/// Return the DOM Instance object with all the fields filled in according to this object.
		/// </summary>
		protected abstract DomInstance InternalToInstance();
		/// <summary>
		/// Optional method that runs after the internal ToInstance method runs.
		/// </summary>
		protected virtual void AfterToInstance()
		{
		}

		protected abstract void InitializeProperties();
		/// <summary>
		/// Optional method that runs after the object is constructed and the initialize has ran.
		/// </summary>
		protected virtual void AfterLoad()
		{
		}

		public override int GetHashCode()
		{
			return this.ID.GetHashCode();
		}

		public override bool Equals(object obj)
		{
			return Equals(obj as DomInstanceBase);
		}

		public bool Equals(DomInstanceBase other)
		{
			if (other is null)
			{
				return false;
			}

			if (ReferenceEquals(this, other))
			{
				return true;
			}

			return this.ID.Equals(other.ID);
		}
	}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DOM Code Generator automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DomHelpers
{
	using System;
	using System.Linq;

	using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
	using Skyline.DataMiner.Net.Sections;

	internal abstract class DomSectionBase : IEquatable<DomSectionBase>
	{
		protected Section section;
		protected DomSectionBase(SectionDefinitionID id)
		{
			if (id == null)
				throw new ArgumentNullException("id");
			this.section = new Section(id);
			AfterLoad();
		}

		protected DomSectionBase(SectionDefinition definition)
		{
			if (definition == null)
				throw new ArgumentNullException("definition");
			this.section = new Section(definition);
			AfterLoad();
		}

		protected DomSectionBase(Section section, SectionDefinitionID id)
		{
			if (section == null)
				throw new ArgumentNullException("section");
			if (section.SectionDefinitionID == null)
			{
				throw new ArgumentException("The given section doesn't have a valid SectionDefinitionId.", nameof(section));
			}

			if (!section.SectionDefinitionID.Equals(id))
			{
				throw new ArgumentException($"The given section, is not of type '{nameof(id)}'", nameof(section));
			}

			this.section = section;
			AfterLoad();
		}

		/// <summary>
		/// Gets the section's ID.
		/// </summary>
		public SectionID ID
		{
			get
			{
				return section.ID;
			}
		}

		/// <summary>
		/// Gets the section's Section Definition ID.
		/// </summary>
		public SectionDefinitionID SectionDefinitionID
		{
			get
			{
				return section.SectionDefinitionID;
			}
		}

		/// <summary>
		/// Gets a value indicating whether the section is empty.
		/// </summary>
		/// <value>
		/// <see langword="true"/> if the section doesn't contains any field values, otherwise, <see langword="false"/>.
		/// </value>
		public bool IsEmpty
		{
			get
			{
				return !section.FieldValues.Any();
			}
		}

		public static implicit operator SectionDefinitionID(DomSectionBase sectionBase)
		{
			return sectionBase.section.SectionDefinitionID;
		}

		public static implicit operator SectionDefinition(DomSectionBase sectionBase)
		{
			return sectionBase.section.GetSectionDefinition();
		}

		public static bool operator ==(DomSectionBase left, DomSectionBase right)
		{
			if (left is null)
			{
				return right is null;
			}

			return left.Equals(right);
		}

		public static bool operator !=(DomSectionBase left, DomSectionBase right)
		{
			return !(left == right);
		}

		public override string ToString()
		{
			return $"{this.section.SectionDefinitionID}";
		}

		/// <summary>
		/// Optional method that runs at the end of the constructor.
		/// </summary>
		protected virtual void AfterLoad()
		{
		}

		public virtual Section ToSection()
		{
			BeforeToSection();
			var section = InternalToSection();
			AfterToSection();
			return section;
		}

		/// <summary>
		/// Optional method that runs before the internal ToSection method runs.
		/// </summary>
		protected virtual void BeforeToSection()
		{
		}

		protected virtual Section InternalToSection()
		{
			return this.section;
		}

		/// <summary>
		/// Optional method that runs after the internal ToSection method runs.
		/// </summary>
		protected virtual void AfterToSection()
		{
		}

		public override int GetHashCode()
		{
			return this.ID.GetHashCode();
		}

		public override bool Equals(object obj)
		{
			return Equals(obj as DomSectionBase);
		}

		public bool Equals(DomSectionBase other)
		{
			if (other is null)
			{
				return false;
			}

			if (ReferenceEquals(this, other))
			{
				return true;
			}

			return this.ID.Equals(other.ID);
		}
	}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Dom Editor automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DomHelpers.SlcObject_Linking
{
	using System;
	using System.ComponentModel;

	using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
	using Skyline.DataMiner.Net.Sections;

	internal static class SlcObject_LinkingIds
	{
		public const string ModuleId = "(slc)object_linking";
		public static class Enums
		{
		}

		public static class Sections
		{
			public static class EntityDescriptor
			{
				public static SectionDefinitionID Id { get; } = new SectionDefinitionID(new Guid("75dd33f0-204e-4b51-bec3-3ae57065ebc0"))
				{ ModuleId = "(slc)object_linking" };
				public static FieldDescriptorID ID { get; } = new FieldDescriptorID(new Guid("448ee862-c27e-4a59-8177-0a729066ed00"));
				public static FieldDescriptorID DisplayName { get; } = new FieldDescriptorID(new Guid("1e090b71-79a7-4139-b0b0-4bf54121e5fe"));
				public static FieldDescriptorID ModelName { get; } = new FieldDescriptorID(new Guid("b5c01401-f9aa-4a70-9dc8-6ea074f7ea32"));
				public static FieldDescriptorID SolutionName { get; } = new FieldDescriptorID(new Guid("770cb9d9-7794-45a7-a551-9f1362a7aacc"));
				public static FieldDescriptorID ParentID { get; } = new FieldDescriptorID(new Guid("a2e6974c-226a-4b78-9f74-1980d9957eb7"));
				public static FieldDescriptorID ParentModelName { get; } = new FieldDescriptorID(new Guid("a6652fa8-378a-4746-a490-fa7d8262abe3"));
			}
		}

		public static class Definitions
		{
			public static DomDefinitionId Link { get; } = new DomDefinitionId(new Guid("f0c5a841-498a-4c3c-a4e0-c3c4c162d206"))
			{ ModuleId = "(slc)object_linking" };
		}

		public static class Behaviors
		{
		}
	}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Dom Code Generator automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DomHelpers.SlcObject_Linking
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
	using Skyline.DataMiner.Net.Messages;

	/// <summary>
	/// Represents a wrapper class for accessing a LinkInstance DOM instance.
	/// The <see cref="LinkInstance"/> class provides simplified access to the data and functionality of the underlying DOM instance, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	internal partial class LinkInstance : DomInstanceBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="LinkInstance"/> class. Creates an empty <see cref="LinkInstance"/> instance with default settings.
		/// </summary>
		public LinkInstance() : base(SlcObject_LinkingIds.Definitions.Link)
		{
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="LinkInstance"/> class. Creates an empty <see cref="LinkInstance"/> instance with default settings and a specific ID.
		/// </summary>
		public LinkInstance(Guid id) : base(SlcObject_LinkingIds.Definitions.Link, id)
		{
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="LinkInstance"/> class using the specified <paramref name="domInstance"/> for initializing the object.
		/// </summary>
		/// <param name="domInstance">The <see cref="DomInstance"/> object that provides data for initializing the <see cref="LinkInstance"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public LinkInstance(DomInstance domInstance) : base(domInstance)
		{
			if (!domInstance.DomDefinitionId.Equals(SlcObject_LinkingIds.Definitions.Link))
				throw new ArgumentException($"The given domInstance, is not of type '{nameof(SlcObject_LinkingIds.Definitions.Link)}'", nameof(domInstance));
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Gets or sets the EntityDescriptor section of the DOM Instance.
		/// </summary>
		public IList<EntityDescriptorSection> EntityDescriptor { get; private set; }

		public static explicit operator LinkInstance(DomInstance instance)
		{
			return new LinkInstance(instance);
		}

		/// <summary>
		/// Creates a deep copy of the current <see cref="LinkInstance"/>.
		/// </summary>
		/// <returns>A new <see cref="LinkInstance"/> object that is a deep copy of this instance.</returns>
		public LinkInstance Clone()
		{
			return new LinkInstance((DomInstance)this.ToInstance().Clone());
		}

		/// <summary>
		/// Creates a duplicate of the current <see cref="LinkInstance"/> with a new id.
		/// </summary>
		/// <returns>A new <see cref="LinkInstance"/> object that is a copy of this instance but with a different id.</returns>
		public LinkInstance Duplicate()
		{
			var instance = (DomInstance)this.ToInstance().Clone();
			instance.ID = new DomInstanceId(Guid.NewGuid())
			{ ModuleId = ModuleId };
			foreach (var section in instance.Sections)
			{
				section.ID = new Skyline.DataMiner.Net.Sections.SectionID(Guid.NewGuid());
			}

			return new LinkInstance(instance);
		}

		/// <inheritdoc />
		protected sealed override DomInstance InternalToInstance()
		{
			domInstance.Sections.Clear();
			foreach (var item in EntityDescriptor)
			{
				domInstance.Sections.Add(item.ToSection());
			}

			return domInstance;
		}

		/// <inheritdoc />
		public sealed override void Save(DomHelper helper)
		{
			var exist = helper.DomInstances.Read(DomInstanceExposers.Id.Equal(domInstance.ID)).FirstOrDefault();
			var instance = ToInstance();
			if (exist == null)
			{
				domInstance = helper.DomInstances.Create(instance);
			}
			else
			{
				domInstance = helper.DomInstances.Update(instance);
			}
		}

		protected sealed override void InitializeProperties()
		{
			EntityDescriptor = domInstance.Sections.Where(section => section.SectionDefinitionID.Equals(SlcObject_LinkingIds.Sections.EntityDescriptor.Id)).Select(section => new EntityDescriptorSection(section)).ToList();
		}
	}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DOM Code Generator automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DomHelpers.SlcObject_Linking
{
	using System;
	using System.Collections.Generic;
	using System.Collections.ObjectModel;
	using System.Linq;

	using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
	using Skyline.DataMiner.Net.Apps.Sections.Sections;
	using Skyline.DataMiner.Net.Messages;
	using Skyline.DataMiner.Net.Sections;

	/// <summary>
	/// Represents a wrapper class for accessing a EntityDescriptorSection section.
	/// The <see cref="EntityDescriptorSection"/> class provides simplified access to the data and functionality of the underlying DOM section, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	internal partial class EntityDescriptorSection : DomSectionBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="EntityDescriptorSection"/> class. Creates an empty <see cref="EntityDescriptorSection"/> object with default settings.
		/// </summary>
		public EntityDescriptorSection() : base(SlcObject_LinkingIds.Sections.EntityDescriptor.Id)
		{
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="EntityDescriptorSection"/> class using the specified <paramref name="section"/> for initializing the object.
		/// </summary>
		/// <param name="section">The <see cref="Section"/> object that provides data for initializing the <see cref="EntityDescriptorSection"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public EntityDescriptorSection(Section section) : base(section, SlcObject_LinkingIds.Sections.EntityDescriptor.Id)
		{
		}

		/// <summary>
		/// Gets or sets the ID field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String ID
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcObject_LinkingIds.Sections.EntityDescriptor.ID);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcObject_LinkingIds.Sections.EntityDescriptor.ID);
				}
				else
				{
					section.AddOrUpdateValue(SlcObject_LinkingIds.Sections.EntityDescriptor.ID, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the DisplayName field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String DisplayName
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcObject_LinkingIds.Sections.EntityDescriptor.DisplayName);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcObject_LinkingIds.Sections.EntityDescriptor.DisplayName);
				}
				else
				{
					section.AddOrUpdateValue(SlcObject_LinkingIds.Sections.EntityDescriptor.DisplayName, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the ModelName field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String ModelName
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcObject_LinkingIds.Sections.EntityDescriptor.ModelName);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcObject_LinkingIds.Sections.EntityDescriptor.ModelName);
				}
				else
				{
					section.AddOrUpdateValue(SlcObject_LinkingIds.Sections.EntityDescriptor.ModelName, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the SolutionName field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String SolutionName
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcObject_LinkingIds.Sections.EntityDescriptor.SolutionName);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcObject_LinkingIds.Sections.EntityDescriptor.SolutionName);
				}
				else
				{
					section.AddOrUpdateValue(SlcObject_LinkingIds.Sections.EntityDescriptor.SolutionName, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the ParentID field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String ParentID
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcObject_LinkingIds.Sections.EntityDescriptor.ParentID);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcObject_LinkingIds.Sections.EntityDescriptor.ParentID);
				}
				else
				{
					section.AddOrUpdateValue(SlcObject_LinkingIds.Sections.EntityDescriptor.ParentID, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the ParentModelName field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String ParentModelName
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcObject_LinkingIds.Sections.EntityDescriptor.ParentModelName);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcObject_LinkingIds.Sections.EntityDescriptor.ParentModelName);
				}
				else
				{
					section.AddOrUpdateValue(SlcObject_LinkingIds.Sections.EntityDescriptor.ParentModelName, (String)value);
				}
			}
		}

		/// <summary>
		/// Creates a deep copy of the current <see cref="EntityDescriptorSection"/>.
		/// </summary>
		/// <returns>A new <see cref="EntityDescriptorSection"/> object that is a deep copy of this section.</returns>
		public EntityDescriptorSection Clone()
		{
			return new EntityDescriptorSection((Section)this.ToSection().Clone());
		}

		/// <summary>
		/// Creates a duplicate of the current <see cref="EntityDescriptorSection"/> with a new id.
		/// </summary>
		/// <returns>A new <see cref="EntityDescriptorSection"/> object that is a copy of this section but with a different id.</returns>
		public EntityDescriptorSection Duplicate()
		{
			var section = (Section)this.ToSection().Clone();
			section.ID = new SectionID(Guid.NewGuid());
			return new EntityDescriptorSection(section);
		}
	}
}
