<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Skyline.DataMiner.Sdk">
	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<RootNamespace>Skyline.DataMiner.SDM.ObjectLinking.Install</RootNamespace>
	</PropertyGroup>

	<PropertyGroup>
		<DataMinerType>Package</DataMinerType>
		<GenerateDataMinerPackage>True</GenerateDataMinerPackage>
		<MinimumRequiredDmVersion>10.5.9.0 - 16293</MinimumRequiredDmVersion>
		<Version>2.0.2</Version>
		<VersionComment>Initial Version</VersionComment>
		<!-- Do NOT fill in the Organization Token here. This points to either an Environment Variable skyline__sdk__dataminertoken holding the organization token or a Visual Studio User Secret holding the token. -->
		<CatalogPublishKeyName>skyline:sdk:dataminertoken</CatalogPublishKeyName>
		<CatalogDefaultDownloadKeyName>skyline:sdk:dataminertoken</CatalogDefaultDownloadKeyName>
		<UserSecretsId>2c02192b-1308-4e24-874f-041a9689ea39</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Skyline.DataMiner.Core.AppPackageInstaller" />
		<PackageReference Include="Skyline.DataMiner.Core.DataMinerSystem.Automation" />
		<PackageReference Include="Skyline.DataMiner.Dev.Automation" />
		<PackageReference Include="Skyline.DataMiner.SDM.SourceGenerator.Runtime" />
		<PackageReference Include="Skyline.DataMiner.Utils.DOM" />
		<PackageReference Include="Skyline.DataMiner.Utils.SecureCoding" />
		<PackageReference Include="Skyline.DataMiner.Utils.SecureCoding.Analyzers">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="ObjectLinking.CommonTests" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="System.ServiceProcess" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="SetupContent\DevPack\" />
	</ItemGroup>

	<Import Project="..\Shared\Shared.projitems" Label="Shared" />

	<!-- Project reference to ensure build order: Common builds first and copies DLL to SetupContent -->
	<ItemGroup>
		<ProjectReference Include="..\API.Common\ObjectLinking.Common.csproj">
			<ReferenceOutputAssembly>false</ReferenceOutputAssembly>
		</ProjectReference>
		<ProjectReference Include="..\API.Automation\ObjectLinking.Automation.csproj">
			<ReferenceOutputAssembly>false</ReferenceOutputAssembly>
		</ProjectReference>
		<ProjectReference Include="..\API.GQI\ObjectLinking.GQI.csproj">
			<ReferenceOutputAssembly>false</ReferenceOutputAssembly>
		</ProjectReference>
		<ProjectReference Include="..\API.Protocol\ObjectLinking.Protocol.csproj">
			<ReferenceOutputAssembly>false</ReferenceOutputAssembly>
		</ProjectReference>
	</ItemGroup>
</Project>