//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Skyline.DataMiner.SDM.CodeGenerator package.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.SDM.ObjectLinking.Models
{
    using System;
    using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
    using Skyline.DataMiner.Net.Sections;
    using Skyline.DataMiner.SDM;

    [SdmDomMapper]
    internal static class ModelRegistrationDomMapper
    {
        internal const string ModuleId = "(slc)object_linking";
        internal static DomDefinitionId DomDefinitionId = new DomDefinitionId(new Guid("d783118f-0f09-4d7f-bd4c-7986bf8d2a60"))
        {ModuleId = ModuleId};
        internal static class ModelRegistrationProperties
        {
            internal static SectionDefinitionID SectionDefinitionId = new SectionDefinitionID(new Guid("52f8a9fd-ea4d-469d-bfa4-902385d3377c"))
            {ModuleId = ModuleId};
            internal static FieldDescriptorID Name = new FieldDescriptorID(new Guid("d36503c1-62da-4670-a21f-34498bf08af9"));
            internal static FieldDescriptorID DisplayName = new FieldDescriptorID(new Guid("ae48ac14-44a3-4a6e-9964-ec00aa6a17cc"));
            internal static FieldDescriptorID ApiScriptName = new FieldDescriptorID(new Guid("4b97fc51-9671-4506-ab82-50037e24c514"));
            internal static FieldDescriptorID ApiEndpoint = new FieldDescriptorID(new Guid("0c39df20-a051-45a8-ae25-68ff3dab803d"));
            internal static FieldDescriptorID VisualizationEndpoint = new FieldDescriptorID(new Guid("8ec23a0d-0a6e-4bc0-8dfe-5329248b2aef"));
        }
    }
}