//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Skyline.DataMiner.SDM.CodeGenerator package.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.SDM.ObjectLinking
{
	using System;

	using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
	using Skyline.DataMiner.Net.Sections;
	using Skyline.DataMiner.SDM;

	[SdmDomMapper]
	internal static class LinkDomMapper
	{
		internal const string ModuleId = "(slc)object_linking";
		internal static DomDefinitionId DomDefinitionId = new DomDefinitionId(new Guid("f0c5a841-498a-4c3c-a4e0-c3c4c162d206"))
		{ ModuleId = ModuleId };
		internal static class LinkProperties
		{
			internal static SectionDefinitionID SectionDefinitionId = new SectionDefinitionID(new Guid("7efc7e62-b35f-496f-a29e-4ca1e26984ed"))
			{ ModuleId = ModuleId };
			internal static FieldDescriptorID Direction = new FieldDescriptorID(new Guid("ef85d555-3775-40df-bfcc-4bfced030e9f"));
		}

		internal static class Source
		{
			internal static SectionDefinitionID SectionDefinitionId = new SectionDefinitionID(new Guid("9e53f9d3-aba0-440f-b3da-86f03904d17c"))
			{ ModuleId = ModuleId };
			internal static FieldDescriptorID ID = new FieldDescriptorID(new Guid("93f9d4df-0df3-4cff-85cc-8113d6aca2e8"));
			internal static FieldDescriptorID DisplayName = new FieldDescriptorID(new Guid("2f424658-e5a0-444b-91df-967730da9b1d"));
			internal static FieldDescriptorID ModelName = new FieldDescriptorID(new Guid("c590922f-1616-4bac-8c6b-da2a6c20e20b"));
			internal static FieldDescriptorID SolutionID = new FieldDescriptorID(new Guid("e1788cb4-bc96-4ebc-a159-c36bc353ce31"));
			internal static FieldDescriptorID SolutionName = new FieldDescriptorID(new Guid("9236bf02-101b-432c-bce1-bfdfa01df75e"));
			internal static FieldDescriptorID ParentID = new FieldDescriptorID(new Guid("7cd3d763-48ab-44f7-a034-fb70a8a86e69"));
			internal static FieldDescriptorID ParentModelName = new FieldDescriptorID(new Guid("d7575c79-69e8-44a0-87c9-5df5773b47fe"));
			internal static FieldDescriptorID Status = new FieldDescriptorID(new Guid("edaf2762-3530-4d99-89d4-54a896500baa"));
		}

		internal static class Target
		{
			internal static SectionDefinitionID SectionDefinitionId = new SectionDefinitionID(new Guid("81c4a01b-7f1e-4133-b636-923bd22fb3a0"))
			{ ModuleId = ModuleId };
			internal static FieldDescriptorID ID = new FieldDescriptorID(new Guid("6d89652a-9dae-450f-b8b0-e528b8fd09cd"));
			internal static FieldDescriptorID DisplayName = new FieldDescriptorID(new Guid("4e80f19f-305c-4e9f-b385-fc4519199556"));
			internal static FieldDescriptorID ModelName = new FieldDescriptorID(new Guid("9f282167-cf27-49b6-bfab-b6fbcd6b5743"));
			internal static FieldDescriptorID SolutionID = new FieldDescriptorID(new Guid("b3bda264-b510-432a-afd2-23d070709e4b"));
			internal static FieldDescriptorID SolutionName = new FieldDescriptorID(new Guid("46f6627e-9f56-4cef-87f9-488b77a7769b"));
			internal static FieldDescriptorID ParentID = new FieldDescriptorID(new Guid("8578485e-41d7-409a-8818-a99d304ad88b"));
			internal static FieldDescriptorID ParentModelName = new FieldDescriptorID(new Guid("166771e4-af55-4c56-b0f6-bbbd7e25ab49"));
			internal static FieldDescriptorID Status = new FieldDescriptorID(new Guid("d7d59ebf-5d94-4a60-b712-74ea1baf2d28"));
		}

		// We cannot reuse these old guids, since they could already be indexed for some users.
		////internal static class EntityDescriptors
		////{
		////	internal static SectionDefinitionID SectionDefinitionId = new SectionDefinitionID(new Guid("75dd33f0-204e-4b51-bec3-3ae57065ebc0"))
		////	{ ModuleId = "(slc)object_linking" };
		////	internal static FieldDescriptorID ID = new FieldDescriptorID(new Guid("448ee862-c27e-4a59-8177-0a729066ed00"));
		////	internal static FieldDescriptorID DisplayName = new FieldDescriptorID(new Guid("1e090b71-79a7-4139-b0b0-4bf54121e5fe"));
		////	internal static FieldDescriptorID ModelName = new FieldDescriptorID(new Guid("b5c01401-f9aa-4a70-9dc8-6ea074f7ea32"));
		////	internal static FieldDescriptorID SolutionName = new FieldDescriptorID(new Guid("770cb9d9-7794-45a7-a551-9f1362a7aacc"));
		////	internal static FieldDescriptorID ParentID = new FieldDescriptorID(new Guid("a2e6974c-226a-4b78-9f74-1980d9957eb7"));
		////	internal static FieldDescriptorID ParentModelName = new FieldDescriptorID(new Guid("a6652fa8-378a-4746-a490-fa7d8262abe3"));
		////}
	}
}