//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Dom Editor automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DomHelpers.SlcObject_Linking
{
	using System;
	using System.ComponentModel;

	using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
	using Skyline.DataMiner.Net.Sections;

	public static class SlcObject_LinkingIds
	{
		public const string ModuleId = "(slc)object_linking";
		public static class Sections
		{
			public static class Entity
			{
				public static SectionDefinitionID Id { get; } = new SectionDefinitionID(new Guid("75dd33f0-204e-4b51-bec3-3ae57065ebc0"))
				{ ModuleId = "(slc)object_linking" };
				public static FieldDescriptorID ID { get; } = new FieldDescriptorID(new Guid("448ee862-c27e-4a59-8177-0a729066ed00"));
				public static FieldDescriptorID DisplayName { get; } = new FieldDescriptorID(new Guid("1e090b71-79a7-4139-b0b0-4bf54121e5fe"));
				public static FieldDescriptorID ModelName { get; } = new FieldDescriptorID(new Guid("b5c01401-f9aa-4a70-9dc8-6ea074f7ea32"));
				public static FieldDescriptorID SolutionName { get; } = new FieldDescriptorID(new Guid("770cb9d9-7794-45a7-a551-9f1362a7aacc"));
				public static FieldDescriptorID ParentID { get; } = new FieldDescriptorID(new Guid("a2e6974c-226a-4b78-9f74-1980d9957eb7"));
				public static FieldDescriptorID ParentModelName { get; } = new FieldDescriptorID(new Guid("a6652fa8-378a-4746-a490-fa7d8262abe3"));
			}
		}

		public static class Definitions
		{
			public static DomDefinitionId Link { get; } = new DomDefinitionId(new Guid("f0c5a841-498a-4c3c-a4e0-c3c4c162d206"))
			{ ModuleId = "(slc)object_linking" };
		}

		public static class Behaviors
		{
		}
	}
}