//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Skyline.DataMiner.SDM.CodeGenerator package.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.SDM.ObjectLinking
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Skyline.DataMiner.Net;
	using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
	using Skyline.DataMiner.Net.Apps.Sections.Sections;
	using Skyline.DataMiner.Net.Helper;
	using Skyline.DataMiner.Net.ManagerStore;
	using Skyline.DataMiner.Net.Messages;
	using Skyline.DataMiner.Net.Messages.SLDataGateway;
	using Skyline.DataMiner.Net.Sections;
	using Skyline.DataMiner.Net.SubscriptionFilters;
	using Skyline.DataMiner.SDM;

	using SLDataGateway.API.Querying;
	using SLDataGateway.API.Types.Querying;

	internal partial class LinkDomRepository : IBulkRepository<Link>
	{
		private readonly IConnection connection;
		private readonly DomHelper helper;
		public LinkDomRepository(IConnection connection)
		{
			this.connection = connection;
			this.helper = new DomHelper(connection.HandleMessages, LinkDomMapper.ModuleId);
		}

		public Link Create(Link createObject)
		{
			if (createObject is null)
			{
				throw new ArgumentNullException(nameof(createObject));
			}

			var instance = ToInstance(createObject);
			instance = helper.DomInstances.Create(instance);
			return FromInstance(instance);
		}

		public IReadOnlyCollection<Link> Create(IEnumerable<Link> createObjects)
		{
			if (createObjects is null || !createObjects.Any())
			{
				return Array.Empty<Link>();
			}

			// Check if some of the objects already exist
			var existing = new HashSet<string>();
			foreach (var batch in createObjects.Batch(500))
			{
				existing.UnionWith(Read(new ORFilterElement<Link>(batch.Select(obj => LinkExposers.Identifier.Equal(obj.Identifier)).ToArray())).Select(obj => obj.Identifier));
			}

			// Create the remainder
			var SuccessfulItems = new List<Link>();
			var failures = new Dictionary<string, Exception>();
			var objects = createObjects.Where(obj => !existing.Contains(obj.Identifier)).ToDictionary(obj => obj.Identifier);
			foreach (var batch in createObjects.Select(ToInstance).Batch(helper.DomInstances.MaxAmountBulkOperation))
			{
				helper.DomInstances.TryCreateOrUpdate(batch.ToList(), out var result);
				foreach (var failure in result.UnsuccessfulIds)
				{
					failures.Add(failure.Id.ToString(), new CrudFailedException(result.TraceDataPerItem[failure]));
				}

				foreach (var success in result.SuccessfulItems)
				{
					SuccessfulItems.Add(FromInstance(success));
				}
			}

			// If everything went fine, return the successful creations
			if (!existing.Any() && !failures.Any())
			{
				return SuccessfulItems;
			}

			// Otherwise, build and throw an exception
			var exceptionBuilder = new SdmBulkCrudException<Link>.Builder();
			foreach (var obj in createObjects)
			{
				if (existing.Contains(obj.Identifier))
				{
					exceptionBuilder.AddFailed(obj, new SdmCrudException<Link>(obj, $"Could not create Link with guid: '{obj.Identifier}', it already exists."));
					continue;
				}

				if (failures.ContainsKey(obj.Identifier))
				{
					exceptionBuilder.AddFailed(obj, failures[obj.Identifier]);
					continue;
				}

				exceptionBuilder.AddSuccessful(obj);
			}

			throw exceptionBuilder.Build();
		}

		public IReadOnlyCollection<Link> CreateOrUpdate(IEnumerable<Link> items)
		{
			if (items is null || !items.Any())
			{
				return Array.Empty<Link>();
			}

			var successful = new List<Link>();
			var exceptionBuilder = new SdmBulkCrudException<Link>.Builder();
			var objects = items.ToDictionary(obj => obj.Identifier);
			foreach (var batch in items.Select(ToInstance).Batch(helper.DomInstances.MaxAmountBulkOperation))
			{
				helper.DomInstances.TryCreateOrUpdate(batch.ToList(), out var result);
				foreach (var failure in result.UnsuccessfulIds)
				{
					exceptionBuilder.AddFailed(objects[failure.Id.ToString()], new CrudFailedException(result.TraceDataPerItem[failure]));
				}

				foreach (var success in result.SuccessfulItems)
				{
					var item = FromInstance(success);
					exceptionBuilder.AddSuccessful(item);
					successful.Add(item);
				}
			}

			if (exceptionBuilder.HasFailure)
			{
				throw exceptionBuilder.Build();
			}

			return successful;
		}

		public long Count(FilterElement<Link> filter)
		{
			if (filter is null)
			{
				throw new ArgumentNullException(nameof(filter));
			}

			var domFilter = TranslateFullFilter(filter);
			domFilter = domFilter.AND(DomInstanceExposers.DomDefinitionId.Equal(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.DomDefinitionId.Id));
			return helper.DomInstances.Count(domFilter);
		}

		public long Count(IQuery<Link> query)
		{
			if (query is null)
			{
				throw new ArgumentNullException(nameof(query));
			}

			var domFilter = TranslateFullFilter(query.Filter);
			domFilter = domFilter.AND(DomInstanceExposers.DomDefinitionId.Equal(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.DomDefinitionId.Id));
			var domOrder = TranslateFullOrderBy(query.Order);
			var domQuery = query.WithFilter(domFilter).WithOrder(domOrder);
			return helper.DomInstances.Count(domQuery);
		}

		public IEnumerable<Link> Read(FilterElement<Link> filter)
		{
			if (filter is null)
			{
				throw new ArgumentNullException(nameof(filter));
			}

			var domFilter = TranslateFullFilter(filter);
			return Read(domFilter);
		}

		public IEnumerable<Link> Read(IQuery<Link> query)
		{
			if (query is null)
			{
				throw new ArgumentNullException(nameof(query));
			}

			var domFilter = TranslateFullFilter(query.Filter);
			var domOrder = TranslateFullOrderBy(query.Order);
			var domQuery = query.WithFilter(domFilter).WithOrder(domOrder);
			return Read(domQuery);
		}

		public IEnumerable<IPagedResult<Link>> ReadPaged(FilterElement<Link> filter)
		{
			return ReadPaged(filter, 500);
		}

		public IEnumerable<IPagedResult<Link>> ReadPaged(FilterElement<Link> filter, int pageSize)
		{
			if (filter is null)
			{
				throw new ArgumentNullException(nameof(filter));
			}

			if (pageSize <= 0)
			{
				throw new ArgumentOutOfRangeException(nameof(pageSize), "The page size must be 1 or higher");
			}

			var domFilter = TranslateFullFilter(filter);
			var paging = ReadPaged(domFilter, pageSize).GetEnumerator();
			var moveNext = paging.MoveNext();
			var i = 0;
			while (moveNext)
			{
				var page = paging.Current.ToList();
				moveNext = paging.MoveNext();
				var result = new PagedResult<Link>(page, i, pageSize, moveNext);
				yield return result;
				i++;
			}
		}

		public IEnumerable<IPagedResult<Link>> ReadPaged(IQuery<Link> query)
		{
			return ReadPaged(query, 500);
		}

		public IEnumerable<IPagedResult<Link>> ReadPaged(IQuery<Link> query, int pageSize)
		{
			if (query is null)
			{
				throw new ArgumentNullException(nameof(query));
			}

			if (pageSize <= 0)
			{
				throw new ArgumentOutOfRangeException(nameof(pageSize), "The page size must be 1 or higher");
			}

			var domFilter = TranslateFullFilter(query.Filter);
			var domOrder = TranslateFullOrderBy(query.Order);
			var domQuery = query.WithFilter(domFilter).WithOrder(domOrder);
			var paging = ReadPaged(domQuery, pageSize).GetEnumerator();
			var moveNext = paging.MoveNext();
			var i = 0;
			while (moveNext)
			{
				var page = paging.Current.ToList();
				moveNext = paging.MoveNext();
				var result = new PagedResult<Link>(page, i, pageSize, moveNext);
				yield return result;
				i++;
			}
		}

		public Link Update(Link updateObject)
		{
			if (updateObject is null)
			{
				throw new ArgumentNullException(nameof(updateObject));
			}

			var instance = ToInstance(updateObject);
			instance = helper.DomInstances.Update(instance);
			return FromInstance(instance);
		}

		public IReadOnlyCollection<Link> Update(IEnumerable<Link> updateObjects)
		{
			if (updateObjects is null || !updateObjects.Any())
			{
				return Array.Empty<Link>();
			}

			// Check if which objects already exist
			var existing = new HashSet<string>();
			foreach (var batch in updateObjects.Batch(500))
			{
				existing.UnionWith(Read(new ORFilterElement<Link>(batch.Select(obj => LinkExposers.Identifier.Equal(obj.Identifier)).ToArray())).Select(obj => obj.Identifier));
			}

			// Update the existing objects
			var successfulItems = new List<Link>();
			var failures = new Dictionary<string, Exception>();
			var objects = updateObjects.Where(obj => existing.Contains(obj.Identifier)).ToDictionary(obj => obj.Identifier);
			foreach (var batch in updateObjects.Select(ToInstance).Batch(helper.DomInstances.MaxAmountBulkOperation))
			{
				helper.DomInstances.TryCreateOrUpdate(batch.ToList(), out var result);
				foreach (var failure in result.UnsuccessfulIds)
				{
					failures.Add(failure.Id.ToString(), new CrudFailedException(result.TraceDataPerItem[failure]));
				}

				foreach (var success in result.SuccessfulItems)
				{
					successfulItems.Add(FromInstance(success));
				}
			}

			// Check for failures and build exception if needed
			var exceptionBuilder = new SdmBulkCrudException<Link>.Builder();
			foreach (var obj in updateObjects)
			{
				if (!existing.Contains(obj.Identifier))
				{
					exceptionBuilder.AddFailed(obj, new SdmCrudException<Link>(obj, "Could not update a non existing Link"));
					continue;
				}

				if (failures.ContainsKey(obj.Identifier))
				{
					exceptionBuilder.AddFailed(obj, failures[obj.Identifier]);
					continue;
				}

				exceptionBuilder.AddSuccessful(obj);
			}

			if (exceptionBuilder.HasFailure)
			{
				throw exceptionBuilder.Build();
			}

			return successfulItems;
		}

		public void Delete(Link deleteObject)
		{
			if (deleteObject is null)
			{
				throw new ArgumentNullException(nameof(deleteObject));
			}

			var instance = ToInstance(deleteObject);
			helper.DomInstances.Delete(instance);
		}

		public void Delete(IEnumerable<Link> deleteObjects)
		{
			if (deleteObjects is null || !deleteObjects.Any())
			{
				return;
			}

			var exceptionBuilder = new SdmBulkCrudException<Link>.Builder();
			var objects = deleteObjects.ToDictionary(obj => obj.Identifier);
			foreach (var batch in deleteObjects.Select(ToInstance).Batch(helper.DomInstances.MaxAmountBulkOperation))
			{
				helper.DomInstances.TryDelete(batch.ToList(), out var result);
				foreach (var failure in result.UnsuccessfulIds)
				{
					exceptionBuilder.AddFailed(objects[failure.Id.ToString()], new CrudFailedException(result.TraceDataPerItem[failure]));
				}

				foreach (var success in result.SuccessfulIds)
				{
					exceptionBuilder.AddSuccessful(objects[success.Id.ToString()]);
				}
			}

			if (exceptionBuilder.HasFailure)
			{
				throw exceptionBuilder.Build();
			}
		}

		private IEnumerable<Link> Read(FilterElement<DomInstance> domFilter)
		{
			if (domFilter is null)
			{
				throw new ArgumentNullException(nameof(domFilter));
			}

			domFilter = domFilter.AND(DomInstanceExposers.DomDefinitionId.Equal(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.DomDefinitionId.Id));
			var domInstances = helper.DomInstances.Read(domFilter);
			return domInstances.Select(FromInstance);
		}

		private IEnumerable<Link> Read(IQuery<DomInstance> domQuery)
		{
			if (domQuery is null)
			{
				throw new ArgumentNullException(nameof(domQuery));
			}

			var domFilter = domQuery.Filter.AND(DomInstanceExposers.DomDefinitionId.Equal(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.DomDefinitionId.Id));
			domQuery = domQuery.WithFilter(domFilter);
			var domInstances = helper.DomInstances.Read(domQuery);
			return domInstances.Select(FromInstance);
		}

		private IEnumerable<IEnumerable<Link>> ReadPaged(FilterElement<DomInstance> domFilter, int pageSize)
		{
			if (domFilter is null)
			{
				throw new ArgumentNullException(nameof(domFilter));
			}

			domFilter = domFilter.AND(DomInstanceExposers.DomDefinitionId.Equal(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.DomDefinitionId.Id));
			var pagingHelper = helper.DomInstances.PreparePaging(domFilter, pageSize);
			while (pagingHelper.MoveToNextPage())
			{
				yield return pagingHelper.GetCurrentPage().Select(FromInstance);
			}
		}

		private IEnumerable<IEnumerable<Link>> ReadPaged(IQuery<DomInstance> domQuery, int pageSize)
		{
			if (domQuery is null)
			{
				throw new ArgumentNullException(nameof(domQuery));
			}

			var domFilter = domQuery.Filter.AND(DomInstanceExposers.DomDefinitionId.Equal(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.DomDefinitionId.Id));
			domQuery = domQuery.WithFilter(domFilter);
			var pagingHelper = helper.DomInstances.PreparePaging(domQuery, pageSize);
			while (pagingHelper.MoveToNextPage())
			{
				yield return pagingHelper.GetCurrentPage().Select(FromInstance);
			}
		}

		private FilterElement<DomInstance> TranslateFullFilter(FilterElement<Link> filter)
		{
			if (filter is null)
			{
				throw new ArgumentNullException(nameof(filter));
			}

			FilterElement<DomInstance> translated;
			if (filter is ANDFilterElement<Link> and)
			{
				translated = new ANDFilterElement<DomInstance>(and.subFilters.Select(TranslateFullFilter).ToArray());
			}
			else if (filter is ORFilterElement<Link> or)
			{
				translated = new ORFilterElement<DomInstance>(or.subFilters.Select(TranslateFullFilter).ToArray());
			}
			else if (filter is NOTFilterElement<Link> not)
			{
				translated = new NOTFilterElement<DomInstance>(TranslateFullFilter(not));
			}
			else if (filter is TRUEFilterElement<Link>)
			{
				translated = new TRUEFilterElement<DomInstance>();
			}
			else if (filter is FALSEFilterElement<Link>)
			{
				translated = new FALSEFilterElement<DomInstance>();
			}
			else if (filter is ManagedFilterIdentifier managedFilter)
			{
				translated = TranslateFilter(managedFilter);
			}
			else
			{
				throw new NotSupportedException($"Unsupported filter: {filter}");
			}

			return translated;
		}

		private IOrderBy TranslateFullOrderBy(IOrderBy order)
		{
			if (order is null)
			{
				throw new ArgumentNullException(nameof(order));
			}

			var translatedElements = new List<IOrderByElement>();
			foreach (var orderByElement in order.Elements)
			{
				var translated = TranslateOrderBy(orderByElement);
				translatedElements.Add(translated);
			}

			return new OrderBy(translatedElements);
		}

		private FilterElement<DomInstance> TranslateFilter(ManagedFilterIdentifier managedFilter)
		{
			if (managedFilter is null)
			{
				throw new ArgumentNullException(nameof(managedFilter));
			}

			var fieldName = managedFilter.getFieldName().fieldName;
			var comparer = managedFilter.getComparer();
			var value = managedFilter.getValue();
			var translated = CreateFilter(fieldName, comparer, value);
			return translated;
		}

		private IOrderByElement TranslateOrderBy(IOrderByElement orderByElement)
		{
			if (orderByElement is null)
			{
				throw new ArgumentNullException(nameof(orderByElement));
			}

			var fieldName = orderByElement.Exposer.fieldName;
			var sortOrder = orderByElement.SortOrder;
			var naturalSort = orderByElement.Options.NaturalSort;
			var translated = CreateOrderBy(fieldName, sortOrder, naturalSort);
			return translated;
		}

		private Link FromInstance(DomInstance instance)
		{
			var obj = new Link
			{
				Identifier = instance.ID.Id.ToString(),
				CreatedAt = ((ITrackCreatedAt)instance).CreatedAt,
				CreatedBy = ((ITrackCreatedBy)instance).CreatedBy,
				LastModified = ((ITrackLastModified)instance).LastModified,
				LastModifiedBy = ((ITrackLastModifiedBy)instance).LastModifiedBy
			};
			var _linkpropertiesSection = instance.Sections.FirstOrDefault(s => s.SectionDefinitionID.Equals(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.LinkProperties.SectionDefinitionId));
			if (_linkpropertiesSection != default)
			{
				var _direction = _linkpropertiesSection.GetValue<int>(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.LinkProperties.Direction);
				if (_direction != null)
				{
					obj.Direction = (Skyline.DataMiner.SDM.ObjectLinking.Models.LinkDirection)_direction.Value;
				}
			}

			var _sourceSection = instance.Sections.FirstOrDefault(s => s.SectionDefinitionID.Equals(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Source.SectionDefinitionId));
			if (_sourceSection != default)
			{
				obj.Source = new Skyline.DataMiner.SDM.ObjectLinking.EntityDescriptor();
				var _sourceid = _sourceSection.GetValue<string>(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Source.ID);
				if (_sourceid != null)
				{
					obj.Source.ID = _sourceid.Value;
				}

				var _sourcedisplayname = _sourceSection.GetValue<string>(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Source.DisplayName);
				if (_sourcedisplayname != null)
				{
					obj.Source.DisplayName = _sourcedisplayname.Value;
				}

				var _sourcemodelname = _sourceSection.GetValue<string>(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Source.ModelName);
				if (_sourcemodelname != null)
				{
					obj.Source.ModelName = _sourcemodelname.Value;
				}

				var _sourcesolutionname = _sourceSection.GetValue<string>(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Source.SolutionName);
				if (_sourcesolutionname != null)
				{
					obj.Source.SolutionName = _sourcesolutionname.Value;
				}

				var _sourceparentid = _sourceSection.GetValue<string>(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Source.ParentID);
				if (_sourceparentid != null)
				{
					obj.Source.ParentID = _sourceparentid.Value;
				}

				var _sourceparentmodelname = _sourceSection.GetValue<string>(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Source.ParentModelName);
				if (_sourceparentmodelname != null)
				{
					obj.Source.ParentModelName = _sourceparentmodelname.Value;
				}

				var _sourcestatus = _sourceSection.GetValue<int>(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Source.Status);
				if (_sourcestatus != null)
				{
					obj.Source.Status = (Skyline.DataMiner.SDM.ObjectLinking.EntityStatus)_sourcestatus.Value;
				}
			}

			var _targetSection = instance.Sections.FirstOrDefault(s => s.SectionDefinitionID.Equals(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Target.SectionDefinitionId));
			if (_targetSection != default)
			{
				obj.Target = new Skyline.DataMiner.SDM.ObjectLinking.EntityDescriptor();
				var _targetid = _targetSection.GetValue<string>(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Target.ID);
				if (_targetid != null)
				{
					obj.Target.ID = _targetid.Value;
				}

				var _targetdisplayname = _targetSection.GetValue<string>(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Target.DisplayName);
				if (_targetdisplayname != null)
				{
					obj.Target.DisplayName = _targetdisplayname.Value;
				}

				var _targetmodelname = _targetSection.GetValue<string>(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Target.ModelName);
				if (_targetmodelname != null)
				{
					obj.Target.ModelName = _targetmodelname.Value;
				}

				var _targetsolutionname = _targetSection.GetValue<string>(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Target.SolutionName);
				if (_targetsolutionname != null)
				{
					obj.Target.SolutionName = _targetsolutionname.Value;
				}

				var _targetparentid = _targetSection.GetValue<string>(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Target.ParentID);
				if (_targetparentid != null)
				{
					obj.Target.ParentID = _targetparentid.Value;
				}

				var _targetparentmodelname = _targetSection.GetValue<string>(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Target.ParentModelName);
				if (_targetparentmodelname != null)
				{
					obj.Target.ParentModelName = _targetparentmodelname.Value;
				}

				var _targetstatus = _targetSection.GetValue<int>(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Target.Status);
				if (_targetstatus != null)
				{
					obj.Target.Status = (Skyline.DataMiner.SDM.ObjectLinking.EntityStatus)_targetstatus.Value;
				}
			}

			return obj;
		}

		private DomInstance ToInstance(Link obj)
		{
			Guid id = default(Guid);
			if (!String.IsNullOrEmpty(obj.Identifier))
			{
				id = Guid.Parse(obj.Identifier);
			}
			else
			{
				id = Guid.NewGuid();
			}

			var instance = new DomInstance
			{
				DomDefinitionId = Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.DomDefinitionId,
				ID = new DomInstanceId(id)
				{
					ModuleId = Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.ModuleId
				}
			};
			var _linkproperties = new Section(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.LinkProperties.SectionDefinitionId);
			_linkproperties.AddOrUpdateValue<int>(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.LinkProperties.Direction, (int)obj.Direction);
			instance.Sections.Add(_linkproperties);
			if (obj.Source != null)
			{
				var _source = new Section(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Source.SectionDefinitionId);
				if (obj.Source.ID != default)
				{
					_source.AddOrUpdateValue<string>(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Source.ID, Convert.ToString(obj.Source.ID));
				}

				if (obj.Source.DisplayName != default)
				{
					_source.AddOrUpdateValue<string>(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Source.DisplayName, Convert.ToString(obj.Source.DisplayName));
				}

				if (obj.Source.ModelName != default)
				{
					_source.AddOrUpdateValue<string>(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Source.ModelName, Convert.ToString(obj.Source.ModelName));
				}

				if (obj.Source.SolutionName != default)
				{
					_source.AddOrUpdateValue<string>(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Source.SolutionName, Convert.ToString(obj.Source.SolutionName));
				}

				if (obj.Source.ParentID != default)
				{
					_source.AddOrUpdateValue<string>(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Source.ParentID, Convert.ToString(obj.Source.ParentID));
				}

				if (obj.Source.ParentModelName != default)
				{
					_source.AddOrUpdateValue<string>(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Source.ParentModelName, Convert.ToString(obj.Source.ParentModelName));
				}

				_source.AddOrUpdateValue<int>(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Source.Status, (int)obj.Source.Status);
				instance.Sections.Add(_source);
			}

			if (obj.Target != null)
			{
				var _target = new Section(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Target.SectionDefinitionId);
				if (obj.Target.ID != default)
				{
					_target.AddOrUpdateValue<string>(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Target.ID, Convert.ToString(obj.Target.ID));
				}

				if (obj.Target.DisplayName != default)
				{
					_target.AddOrUpdateValue<string>(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Target.DisplayName, Convert.ToString(obj.Target.DisplayName));
				}

				if (obj.Target.ModelName != default)
				{
					_target.AddOrUpdateValue<string>(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Target.ModelName, Convert.ToString(obj.Target.ModelName));
				}

				if (obj.Target.SolutionName != default)
				{
					_target.AddOrUpdateValue<string>(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Target.SolutionName, Convert.ToString(obj.Target.SolutionName));
				}

				if (obj.Target.ParentID != default)
				{
					_target.AddOrUpdateValue<string>(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Target.ParentID, Convert.ToString(obj.Target.ParentID));
				}

				if (obj.Target.ParentModelName != default)
				{
					_target.AddOrUpdateValue<string>(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Target.ParentModelName, Convert.ToString(obj.Target.ParentModelName));
				}

				_target.AddOrUpdateValue<int>(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Target.Status, (int)obj.Target.Status);
				instance.Sections.Add(_target);
			}

			return instance;
		}

		private FilterElement<DomInstance> CreateFilter(string fieldName, Comparer comparer, object value)
		{
			switch (fieldName)
			{
				case "Identifier":
					return FilterElementFactory.Create<DomInstance>(DomInstanceExposers.Id, comparer, Guid.Parse((string)value));
				case "Direction":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.LinkProperties.Direction), comparer, (int)(Skyline.DataMiner.SDM.ObjectLinking.Models.LinkDirection)value);
				case "LastModified":
					return FilterElementFactory.Create<DomInstance>(DomInstanceExposers.LastModified, comparer, (DateTime)value);
				case "LastModifiedBy":
					return FilterElementFactory.Create<DomInstance>(DomInstanceExposers.LastModifiedBy, comparer, (string)value);
				case "CreatedAt":
					return FilterElementFactory.Create<DomInstance>(DomInstanceExposers.CreatedAt, comparer, (DateTime)value);
				case "CreatedBy":
					return FilterElementFactory.Create<DomInstance>(DomInstanceExposers.CreatedBy, comparer, (string)value);
				case "Source.ID":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Source.ID), comparer, (string)value);
				case "Source.DisplayName":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Source.DisplayName), comparer, (string)value);
				case "Source.ModelName":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Source.ModelName), comparer, (string)value);
				case "Source.SolutionName":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Source.SolutionName), comparer, (string)value);
				case "Source.ParentID":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Source.ParentID), comparer, (string)value);
				case "Source.ParentModelName":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Source.ParentModelName), comparer, (string)value);
				case "Source.Status":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Source.Status), comparer, (int)(Skyline.DataMiner.SDM.ObjectLinking.EntityStatus)value);
				case "Target.ID":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Target.ID), comparer, (string)value);
				case "Target.DisplayName":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Target.DisplayName), comparer, (string)value);
				case "Target.ModelName":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Target.ModelName), comparer, (string)value);
				case "Target.SolutionName":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Target.SolutionName), comparer, (string)value);
				case "Target.ParentID":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Target.ParentID), comparer, (string)value);
				case "Target.ParentModelName":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Target.ParentModelName), comparer, (string)value);
				case "Target.Status":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Target.Status), comparer, (int)(Skyline.DataMiner.SDM.ObjectLinking.EntityStatus)value);
				default:
					throw new NotImplementedException();
			}
		}

		private IOrderByElement CreateOrderBy(string fieldName, SortOrder sortOrder, bool naturalSort = false)
		{
			switch (fieldName)
			{
				case "Identifier":
					return OrderByElementFactory.Create(DomInstanceExposers.Id, sortOrder, naturalSort);
				case "Direction":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.LinkProperties.Direction), sortOrder, naturalSort);
				case "LastModified":
					return OrderByElementFactory.Create(DomInstanceExposers.LastModified, sortOrder, naturalSort);
				case "LastModifiedBy":
					return OrderByElementFactory.Create(DomInstanceExposers.LastModifiedBy, sortOrder, naturalSort);
				case "CreatedAt":
					return OrderByElementFactory.Create(DomInstanceExposers.CreatedAt, sortOrder, naturalSort);
				case "CreatedBy":
					return OrderByElementFactory.Create(DomInstanceExposers.CreatedBy, sortOrder, naturalSort);
				case "Source.ID":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Source.ID), sortOrder, naturalSort);
				case "Source.DisplayName":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Source.DisplayName), sortOrder, naturalSort);
				case "Source.ModelName":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Source.ModelName), sortOrder, naturalSort);
				case "Source.SolutionName":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Source.SolutionName), sortOrder, naturalSort);
				case "Source.ParentID":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Source.ParentID), sortOrder, naturalSort);
				case "Source.ParentModelName":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Source.ParentModelName), sortOrder, naturalSort);
				case "Source.Status":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Source.Status), sortOrder, naturalSort);
				case "Target.ID":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Target.ID), sortOrder, naturalSort);
				case "Target.DisplayName":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Target.DisplayName), sortOrder, naturalSort);
				case "Target.ModelName":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Target.ModelName), sortOrder, naturalSort);
				case "Target.SolutionName":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Target.SolutionName), sortOrder, naturalSort);
				case "Target.ParentID":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Target.ParentID), sortOrder, naturalSort);
				case "Target.ParentModelName":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Target.ParentModelName), sortOrder, naturalSort);
				case "Target.Status":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.ObjectLinking.LinkDomMapper.Target.Status), sortOrder, naturalSort);
				default:
					throw new NotImplementedException();
			}
		}
	}
}