//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Skyline.DataMiner.SDM.CodeGenerator package.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skyline.DataMiner.SDM.ObjectLinking
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Skyline.DataMiner.Net;
	using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
	using Skyline.DataMiner.Net.Apps.Sections.Sections;
	using Skyline.DataMiner.Net.Helper;
	using Skyline.DataMiner.Net.ManagerStore;
	using Skyline.DataMiner.Net.Messages;
	using Skyline.DataMiner.Net.Messages.SLDataGateway;
	using Skyline.DataMiner.Net.Sections;
	using Skyline.DataMiner.Net.SubscriptionFilters;
	using Skyline.DataMiner.SDM;

	using SLDataGateway.API.Querying;
	using SLDataGateway.API.Types.Querying;

	internal sealed partial class LinkDomRepository_Middleware : Skyline.DataMiner.SDM.IBulkRepository<Skyline.DataMiner.SDM.ObjectLinking.Link>
	{
		private readonly Skyline.DataMiner.SDM.IBulkRepository<Skyline.DataMiner.SDM.ObjectLinking.Link> _inner;
		private readonly IMiddlewareMarker<Skyline.DataMiner.SDM.ObjectLinking.Link> _middleware;

		public LinkDomRepository_Middleware(Skyline.DataMiner.SDM.IBulkRepository<Skyline.DataMiner.SDM.ObjectLinking.Link> inner, IMiddlewareMarker<Skyline.DataMiner.SDM.ObjectLinking.Link> middleware)
		{
			_inner = inner ?? throw new ArgumentNullException(nameof(inner));
			_middleware = middleware;
		}

		public IEnumerable<IPagedResult<Skyline.DataMiner.SDM.ObjectLinking.Link>> ReadPaged(FilterElement<Skyline.DataMiner.SDM.ObjectLinking.Link> filter)
		{
			if (_middleware is IPageableMiddleware<Skyline.DataMiner.SDM.ObjectLinking.Link> middleware)
			{
				return middleware.OnReadPaged(filter, _inner.ReadPaged);
			}
			else
			{
				return _inner.ReadPaged(filter);
			}
		}

		public IEnumerable<IPagedResult<Skyline.DataMiner.SDM.ObjectLinking.Link>> ReadPaged(IQuery<Skyline.DataMiner.SDM.ObjectLinking.Link> query)
		{
			if (_middleware is IPageableMiddleware<Skyline.DataMiner.SDM.ObjectLinking.Link> middleware)
			{
				return middleware.OnReadPaged(query, _inner.ReadPaged);
			}
			else
			{
				return _inner.ReadPaged(query);
			}
		}

		public IEnumerable<IPagedResult<Skyline.DataMiner.SDM.ObjectLinking.Link>> ReadPaged(FilterElement<Skyline.DataMiner.SDM.ObjectLinking.Link> filter, int pageSize)
		{
			if (_middleware is IPageableMiddleware<Skyline.DataMiner.SDM.ObjectLinking.Link> middleware)
			{
				return middleware.OnReadPaged(filter, pageSize, _inner.ReadPaged);
			}
			else
			{
				return _inner.ReadPaged(filter, pageSize);
			}
		}

		public IEnumerable<IPagedResult<Skyline.DataMiner.SDM.ObjectLinking.Link>> ReadPaged(IQuery<Skyline.DataMiner.SDM.ObjectLinking.Link> query, int pageSize)
		{
			if (_middleware is IPageableMiddleware<Skyline.DataMiner.SDM.ObjectLinking.Link> middleware)
			{
				return middleware.OnReadPaged(query, pageSize, _inner.ReadPaged);
			}
			else
			{
				return _inner.ReadPaged(query, pageSize);
			}
		}

		public IEnumerable<Skyline.DataMiner.SDM.ObjectLinking.Link> Read(FilterElement<Skyline.DataMiner.SDM.ObjectLinking.Link> filter)
		{
			if (_middleware is IReadableMiddleware<Skyline.DataMiner.SDM.ObjectLinking.Link> middleware)
			{
				return middleware.OnRead(filter, _inner.Read);
			}
			else
			{
				return _inner.Read(filter);
			}
		}

		public IEnumerable<Skyline.DataMiner.SDM.ObjectLinking.Link> Read(IQuery<Skyline.DataMiner.SDM.ObjectLinking.Link> query)
		{
			if (_middleware is IReadableMiddleware<Skyline.DataMiner.SDM.ObjectLinking.Link> middleware)
			{
				return middleware.OnRead(query, _inner.Read);
			}
			else
			{
				return _inner.Read(query);
			}
		}

		public long Count(FilterElement<Skyline.DataMiner.SDM.ObjectLinking.Link> filter)
		{
			if (_middleware is ICountableMiddleware<Skyline.DataMiner.SDM.ObjectLinking.Link> middleware)
			{
				return middleware.OnCount(filter, _inner.Count);
			}
			else
			{
				return _inner.Count(filter);
			}
		}

		public long Count(IQuery<Skyline.DataMiner.SDM.ObjectLinking.Link> query)
		{
			if (_middleware is ICountableMiddleware<Skyline.DataMiner.SDM.ObjectLinking.Link> middleware)
			{
				return middleware.OnCount(query, _inner.Count);
			}
			else
			{
				return _inner.Count(query);
			}
		}

		public IReadOnlyCollection<Skyline.DataMiner.SDM.ObjectLinking.Link> Create(IEnumerable<Skyline.DataMiner.SDM.ObjectLinking.Link> oToCreate)
		{
			if (_middleware is IBulkCreatableMiddleware<Skyline.DataMiner.SDM.ObjectLinking.Link> middleware)
			{
				return middleware.OnCreate(oToCreate, _inner.Create);
			}
			else
			{
				return _inner.Create(oToCreate);
			}
		}

		public Skyline.DataMiner.SDM.ObjectLinking.Link Create(Skyline.DataMiner.SDM.ObjectLinking.Link oToCreate)
		{
			if (_middleware is ICreatableMiddleware<Skyline.DataMiner.SDM.ObjectLinking.Link> middleware)
			{
				return middleware.OnCreate(oToCreate, _inner.Create);
			}
			else
			{
				return _inner.Create(oToCreate);
			}
		}

		public IReadOnlyCollection<Skyline.DataMiner.SDM.ObjectLinking.Link> Update(IEnumerable<Skyline.DataMiner.SDM.ObjectLinking.Link> oToUpdate)
		{
			if (_middleware is IBulkUpdatableMiddleware<Skyline.DataMiner.SDM.ObjectLinking.Link> middleware)
			{
				return middleware.OnUpdate(oToUpdate, _inner.Update);
			}
			else
			{
				return _inner.Update(oToUpdate);
			}
		}

		public Skyline.DataMiner.SDM.ObjectLinking.Link Update(Skyline.DataMiner.SDM.ObjectLinking.Link oToUpdate)
		{
			if (_middleware is IUpdatableMiddleware<Skyline.DataMiner.SDM.ObjectLinking.Link> middleware)
			{
				return middleware.OnUpdate(oToUpdate, _inner.Update);
			}
			else
			{
				return _inner.Update(oToUpdate);
			}
		}

		public void Delete(IEnumerable<Skyline.DataMiner.SDM.ObjectLinking.Link> oToDelete)
		{
			if (_middleware is IBulkDeletableMiddleware<Skyline.DataMiner.SDM.ObjectLinking.Link> middleware)
			{
				middleware.OnDelete(oToDelete, _inner.Delete);
			}
			else
			{
				_inner.Delete(oToDelete);
			}
		}

		public void Delete(Skyline.DataMiner.SDM.ObjectLinking.Link oToDelete)
		{
			if (_middleware is IDeletableMiddleware<Skyline.DataMiner.SDM.ObjectLinking.Link> middleware)
			{
				middleware.OnDelete(oToDelete, _inner.Delete);
			}
			else
			{
				_inner.Delete(oToDelete);
			}
		}
		public System.Collections.Generic.IReadOnlyCollection<Skyline.DataMiner.SDM.ObjectLinking.Link> CreateOrUpdate(System.Collections.Generic.IEnumerable<Skyline.DataMiner.SDM.ObjectLinking.Link> oToCreateOrUpdate)
		{
			return _inner.CreateOrUpdate(oToCreateOrUpdate);
		}

	}
}
